---
- name: unblock access to iRODS for CyVerse users
  hosts: irods
  become: true
  gather_facts: true
  tasks:
    - include: tasks/set_iptables_input_chain.yml

    - name: unblock port 1247 for 128.196.38.0
      lineinfile:
        dest: /etc/sysconfig/iptables
        insertbefore: -A {{ iptables_input_chain }} .*-m state --state NEW -m tcp .*--dport 1247
        line: -A {{ iptables_input_chain }} -m state --state NEW -m tcp -p tcp -s 128.196.38.0/25 --dport 1247 -j ACCEPT
      register: acccess

    - name: reload iptables
      service:
        name: iptables
        state: restarted  # XXX reloaded fails
      when: access|changed 
