---
- name: determine the name of the iptables INPUT chain
  shell: |
    sed --quiet 's/^-A \(.*INPUT\) .*-m state --state NEW -m tcp .*--dport 1247 .*$/\1/p' \
        /etc/sysconfig/iptables \
      | head --lines 1
  args:   
    warn: false
  register: sed
  changed_when: false

- name: set iptables_input_chain
  set_fact:
    iptables_input_chain: "{{ sed.stdout }}"

