---
# vars:
#   group: <resource group name>
#   members:
#     - <resource 1 name>
#     - <resource 2 name>
#     ...
- name: remove resource group {{ group }}
  shell: |
    if iRODS/clients/icommands/bin/ilsresc {{ group }}   
    then
      iRODS/clients/icommands/bin/iadmin rfrg {{ group }} {{ item }}
    fi
  with_items: "{{ members }}"
  register: response

- name: verify {{ group }} gone
  shell: |
    if iRODS/clients/icommands/bin/ilsresc {{ group }}
    then
      exit 1
    else
      exit 0
    fi
